on: [push]

jobs:

  Build:
    runs-on: ubuntu-latest
    name: A job to test the oryks code coverage action

    steps:

      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip

          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi 

      - name: Test with oryks code coverage
        id: oryks-code-coverage
        uses: twyle/oryks-code-coverage@v1.0.1
